---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: grafana
  namespace: grafana
spec:
  hosts:
    - "grafana.${cluster_subdomain}"
  gateways:
    - istio-ingress/wildcard-gateway
  http:
    - match: []
      route:
        - destination:
            host: grafana.grafana.svc.cluster.local
            port:
              number: 80
