apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/cloudnative-pg
  - ../../base/istio
patches:
  - path: hetznerk3s.yaml
  - path: cnpg-delete.yaml
  - path: istio-delete.yaml
  - path: istio-delete2.yaml
